<a href="https://colab.research.google.com/github/Akashbansal07/flappy-bird-game/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5])
print (arr)
print (type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(np.__version__)

1.23.5


In [8]:
import numpy as np
x=np.array(56)
y=np.array([1,2,3,4])
z=np.array([[1,2,3],[4,5,6]])
w=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[8,9,0]]])
print(x.ndim)
print(y.ndim)
print(z.ndim)
print(w.ndim)

0
1
2
3


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8], ndmin=5)
print(arr)
print('number of dimensions :',arr.ndim)

[[[[[1 2 3 4 5 6 7 8]]]]]
number of dimensions : 5


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[3],arr[0])


4 1


In [19]:
import numpy as np
arr=np.array([[1,2,3,4,5,8,9],[1,3,4,5,6,7,8]])
print(arr[1,3])

5


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[3,4,5],[7,4,6],[34,6,34]],[[1,2,3],[6,3,5],[9,5,3],[54,43,87]]])
print(arr[1,3,0])
print(arr[0,-1])

array slicing


In [1]:
[start:end]
[start:end:step]

SyntaxError: invalid syntax (<ipython-input-1-47006d629f60>, line 1)

In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:7])
print(arr[1:])
print(arr[:7])
print(arr[-6:])
print(arr[0::2])
print(arr[0::1])
print(arr[0::4])

[3 4 5 6 7]
[2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]
[4 5 6 7 8 9]
[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]
[1 5 9]


In [20]:
import numpy as np
arr=np.array([[1,2,3,4,5,6],[3,4,5,6,7,8],[2,3,4,56,7,7]])
print(arr[:,3])
print(arr[:,:])
print(arr[0:3,:])
print(arr.shape)

[ 4  6 56]
[[ 1  2  3  4  5  6]
 [ 3  4  5  6  7  8]
 [ 2  3  4 56  7  7]]
[[ 1  2  3  4  5  6]
 [ 3  4  5  6  7  8]
 [ 2  3  4 56  7  7]]
(3, 6)


copy vs view

In [19]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=arr.copy()
y=arr.view()
arr[0]=34
print(arr)
print(x)
print(y)

[34  2  3  4  5  6  7  8]
[1 2 3 4 5 6 7 8]
[34  2  3  4  5  6  7  8]


In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
newarr=arr.reshape(2,2,4)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


Array iteration


In [36]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4],[5,6,7],[4,8,6]]])
for x in arr:
  print(x)
for p in arr:
  for y in p:
    for z in y:
      print(z)

print('---')
for x in np.nditer(arr):
  print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3 4]
 [5 6 7]
 [4 8 6]]
1
2
3
4
5
6
7
8
9
2
3
4
5
6
7
4
8
6
---
1
2
3
4
5
6
7
8
9
2
3
4
5
6
7
4
8
6


In [39]:
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'4'
b'8'
b'6'
